apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config: |
    client-id = {{ required "traefikForwardAuth.clientId is required" .Values.traefikForwardAuth.clientId }}
    user-cookie-name = {{ required "traefikForwardAuth.userCookieName is required" .Values.traefikForwardAuth.userCookieName }}
    {{ .Values.traefikForwardAuth.extraConfig | nindent 4 }}
