apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config: |
    rule.path.action = allow
    rule.path.rule = Path(`/favicon.ico`)
    rule.prefix.action = allow
    rule.prefix.rule = PathPrefix(`/dex/`, `/dex-k8s-authenticator`)
