apiVersion: v1
kind: Secret
metadata:
  name: {{ template "traefik-forward-auth.fullname" . }}
type: Opaque
data:
  clientSecret: {{ required "traefikForwardAuth.clientSecret is required" .Values.traefikForwardAuth.clientSecret.value | b64enc | quote }}
  secret: {{ required "traefikForwardAuth.secret is required" .Values.traefikForwardAuth.secret | b64enc | quote }}
